version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:root@db:5000/node_postgres"
      JWT_SECRET: "your_secret_key"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npx prisma migrate deploy && npm start"

volumes:
  pgdata:
