version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:root@db:5432/node_postgres"
      JWT_SECRET: "your_secret_key"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npx prisma migrate deploy && npm start"

#  http://localhost:5000/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
# http://localhost:8080/browser
volumes:
  pgdata:
